### ISSUE TITLE
Can't run docker through VPN

### ISSUE THREAD

**Issue by ryandikdan** [TeamPiped/Piped-Docker#46]
Hello, love this so much. I got it working with very minor adjustments before, but I was hoping to run the proxy and backend behind a VPN (I have proton VPN). When I did this with gluetun I got an error on the backend saying Failed to get country even though I set the server city:

```
Failed to get country from YouTube!
org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
        at org.postgresql.Driver.makeConnection(Driver.java:446)
        at org.postgresql.Driver.connect(Driver.java:298)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
        at me.kavin.piped.utils.LiquibaseHelper.init(LiquibaseHelper.java:32)
        at me.kavin.piped.Main.main(Main.java:82)
Caused by: java.net.UnknownHostException: postgres
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:757)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
        at org.postgresql.core.PGStream.<init>(PGStream.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
```

I'm pretty confident that the issue is with the network_mode to the gluetun instance, since when I remove it, it works fine. 

(On a side note, I'm just wondering if there's a way to make an instance private or only allow specific log ins). Thanks!

**Comment by Bnyro** [comment]
> On a side note, I'm just wondering if there's a way to make an instance private or only allow specific log ins
>
No, you would need to configure your reverse proxy (e.g. nginx) to use Basic Auth yourself.

I can't unfortunately help with the described issue, please ask at the Matrix room if it still exists. The issue tracker is not the right place to ask for support.
